name: Test Mixed with 3.13
on:
  schedule:
    # at 2:20am on Sundays
    - cron: 20 2 * * 0
  workflow_dispatch:
jobs:
  test-mixed-clusters:
    name: Test mixed clusters
    strategy:
      fail-fast: false
      matrix:
        erlang_version:
        - '26'
        elixir_version:
        - '1.18'
        metadata_store:
          - mnesia
    uses: ./.github/workflows/test-make-tests.yaml
    with:
      erlang_version: ${{ matrix.erlang_version }}
      elixir_version: ${{ matrix.elixir_version }}
      previous_version: 'tags/v3.13.7'
      metadata_store: ${{ matrix.metadata_store }}
      mixed_clusters: true
